### ISSUE TITLE
Routes are not protected from bugs 

### ISSUE THREAD

**Issue by ArunTeltia** [ProjectSakura/Mirai#1]
There is a need to put every route in try-catch block , because right now the data is just assumed to be always fetched, there is a need of error handling to avoid server getting down.

**Comment by vmk8826** [comment]
can you assign it to me as I am a GSoC 2021 aspirant

**Comment by ArunTeltia** [comment]
Yeah Sure Ask me if you get stuck in any place

**Comment by vmk8826** [comment]
can you add GSoC as tag

**Comment by ArunTeltia** [comment]
Yeah sure btw its gssoc not gsoc 😊

**Comment by vmk8826** [comment]
okay

**Comment by priyanshu20** [comment]
Is this a stale issue ? I can complete this If you like

**Comment by ArunTeltia** [comment]
Okay go for it @priyanshu20

**Comment by ArunTeltia** [comment]
@vmk8826 is a little late I will assig it to you
