### ISSUE TITLE
Improve UI of the search bar

### ISSUE THREAD

**Issue by FireQueen-3010** [ProjectSakura/Mirai#17]
The UI of the search can be made visually more appealing.
![image](https://user-images.githubusercontent.com/59244300/112710835-fdb5b400-8ee9-11eb-9aa9-4e9f38386b63.png)

**Comment by FireQueen-3010** [comment]
Please assign me this under gssoc'21 @ArunTeltia @LordShenron

**Comment by singhayushh** [comment]
Kindly notify about what changes you'll be making to make it more appealing. It'll be better if you provide a screenshot of a similar design that you have in mind.

**Comment by FireQueen-3010** [comment]
I would like to propose these changes @singhayushh @ArunTeltia @LordShenron  :
1) Add a hover effect to the drop-down list.
2) change color of the search bar when it is on hover and focus mode (while user is typing)
3) Change the font and and font colors
4) Give the whole search bar a glowing box shadow.

**Comment by ArunTeltia** [comment]
Lets assign the issue you can start woking on it @FireQueen-3010

**Comment by FireQueen-3010** [comment]
Thank you :)
