### ISSUE TITLE
Adding genre to the anime list.

### ISSUE THREAD

**Issue by recursiveway** [ProjectSakura/Mirai#23]
It will categorize the anime based on genre.

**Comment by ArunTeltia** [comment]
Hmmm sounds interesting to me will work on it thank you for the suggestion @bug-debug-done

**Comment by recursiveway** [comment]
Okay

**Comment by ArunTeltia** [comment]
Wanna work on it @bug-debug-done

**Comment by recursiveway** [comment]
Yes I want work on it @ArunTeltia

**Comment by ArunTeltia** [comment]
Done Let me know if you have any problems

**Comment by subhangi2731** [comment]
@ArunTeltia I want to work on this please assign me
