### ISSUE TITLE
add contributing.md

### ISSUE THREAD

**Issue by khareyash05** [ProjectSakura/Mirai#28]
Hi! I would like tocreate a file  contributing.md add the following -
Difference between GIT and GITHUB
How to clone,fork repository
How to create a branch and then use git push to push to repo
Create a PR
Squash commits in a single issue into one
Updating the forked and local repo as the updations are made in the upstream

**Comment by ArunTeltia** [comment]
If you want to work on contributors section please check contributors repo we are building that website specially for our precious contributors

I dont think we need a contributing.md for this project but thank you for your thought
