### ISSUE TITLE
Light Novel Scraping 

### ISSUE THREAD

**Issue by ArunTeltia** [ProjectSakura/Mirai#3]
There is a need for researching for the best novel reading website that can be scraped easily 

Here is one light novel website : https://www.lightnovelworld.com/

**Comment by Abhi-1313** [comment]
i will do that

**Comment by ArunTeltia** [comment]
Yes go for it @Abhi-1313 Assigning this issue to you :D

**Comment by Abhi-1313** [comment]
@ArunTeltia here are some good novel reading website
https://allnovel.net/
https://manybooks.net/
https://www.gutenberg.org/
and light novel website
https://novelonlinefull.com/
https://www.readlightnovel.org/
https://kisslightnovels.info/

**Comment by ArunTeltia** [comment]
OHO wow can you check, how many of them are protected by cloudflare, cloudflare dont allow the images to get scraped 
It gave one of the 1020 error while scraping

PS: Solid Work tho thank you @Abhi-1313

**Comment by Abhi-1313** [comment]
@ArunTeltia  ,here websites which are not protected by cloudflare
https://www.gutenberg.org/
https://www.smashwords.com/
https://www.bookrix.com/

**Comment by ArunTeltia** [comment]
Thank you @Abhi-1313, I have noted the websites will be closing the issue now thank you contributing
