### ISSUE TITLE
The navbar should hide from viewmanga

### ISSUE THREAD

**Issue by ArunTeltia** [ProjectSakura/Mirai#5]
The navbar for this website is relatively big, and which is taking a lot of space for the website we want to make the position of the navbar fixed such that scrollbar will only be present at the top of the page

**Comment by Vishal1003** [comment]
@ArunTeltia  I can see that the navbar is already fixed (position) to the top (on scrolling) . If I'm not wrong you want to remove that. Right? (i.e static/default behavior so that it is not visible on scrolling down. )

**Comment by ArunTeltia** [comment]
Yeah thats right want to work on that issue @Vishal1003 ?

**Comment by Vishal1003** [comment]
Yes. Kindly assign me this issue

**Comment by ArunTeltia** [comment]
closed by #6
