### ISSUE TITLE
End point controllers refactoring

### ISSUE THREAD

**Issue by singhayushh** [ProjectSakura/Mirai#7]
I am willing to take up this issue.

I have another suggestion regarding the code modularity. Currently the controller functions for each of the routes are written right inside the route definition. Example:
```js
router.get("/", function (req, res, next) {
  request(
    "https://www.gogoanime1.com/search/topSearch?q=" + req.query.q,
    (error, response, html) => {
      res.send(response.body);
    }
  );
});
```
A good convention to follow is to create a controllers/ directory and have all these controller functions (let's call the above handler function as topSearchHandler) in there so that the api end point just has to call the function:

```
router.get("/", topSearchHandler)
```

_Originally posted by @singhayushh in https://github.com/ProjectSakura/Mirai/issues/2#issuecomment-794932074_

**Comment by singhayushh** [comment]
Since the two issues (#2 and #7) are closely related, I have worked on them simultaneously. All changes have been made and I'll be creating a Pull Request very soon.

**Comment by ArunTeltia** [comment]
Kudos to you @singhayushh for this PR , the code is already looking much more organized🙌

**Comment by singhayushh** [comment]
> Kudos to you @singhayushh for this PR , the code is already looking much more organized

Thank you! Happy to have helped ✌🏼
